version: '3'
services:
  web1:
    build:
      context: ./web1
    restart: always
    ports:
      - "8081:80"
    networks:
      - mynetworkbalancer
    depends_on:
      - mysql  # web1 depende de MySQL

  web2:
    build:
      context: ./web2
    ports:
      - "8082:80"
    networks:
      - mynetworkbalancer
    depends_on:
      - mysql  # web2 depende de MySQL
    restart: always

  mysql:
    build:
      context: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: prueba
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - mynetworkbalancer
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:    
      - "8088:80"
    networks:
      - mynetworkbalancer

networks:
  mynetworkbalancer:

volumes:
  mysql-data:
