version: '3'
services:
  web1:
    build:
      context: ./web1
    ports:
      - "8081:80"
    networks:
      - mynetworkbalancer
    depends_on:
      - mysql  # web1 depende de MySQL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 10s
      timeout: 5s
      retries: 5

  web2:
    build:
      context: ./web2
    ports:
      - "8082:80"
    networks:
      - mynetworkbalancer
    depends_on:
      - mysql  # web2 depende de MySQL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: prueba
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - mynetworkbalancer
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
    ports:    
      - "8088:80"
    networks:
      - mynetworkbalancer

networks:
  mynetworkbalancer:

volumes:
  mysql-data:
